{
  _running=true;
  try {
    while (_running) {
      long startSlice=_context.clock().now();
      _lastSliceRun=startSlice;
      processSlice();
      long endSlice=_context.clock().now();
    }
  }
 catch (  IOException ioe) {
    if (_log.shouldLog(Log.ERROR))     _log.error("Connection runner failed with an IO exception to " + _remoteIdentity.getHash().toBase64(),ioe);
    closeConnection();
  }
catch (  Throwable t) {
    if (_log.shouldLog(Log.ERROR))     _log.error("Somehow we ran into an uncaught exception running the connection!",t);
    closeConnection();
  }
}
