{
  try {
    return super.inf.finished();
  }
 catch (  Exception e) {
    return true;
  }
}
