{
  try {
    main2(args);
  }
 catch (  Exception e) {
    e.printStackTrace();
  }
}
